=== iqb-vocabs/profiles/json_schema/md-profile-config/md-profile-config.schema.json
{
  "$id": "https://w3id.org/iqb/vocabs/md-profile-config.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Metadata Profile Store Config",
  "description": "Configuration file to validate a metadata profile store",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[0-9a-zA-Z_]+$",
      "description": "Identifier for the metadata profile store as part of the uri"
    },
    "creator": {
      "type": "string",
      "description": "Creator as person or institution"
    },
    "title": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "lang": {
            "type": "string",
            "pattern": "^[a-z]+$",
            "description": "Language of the value"
          },
          "value": {
            "type": "string",
            "description": "Language of the value"
          }
        },
        "required": ["lang", "value"]
      },
      "minItems": 1
    },
    "mdOutDir": {
      "type": "string",
      "description": "Folder where the markdown output is written to.",
      "default": "./docs"
    },
    "profiles": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "Name of the profile json files"
      },
      "minItems": 1
    }
  },
  "required": ["id", "title", "creator", "profiles"]
}

=== iqb-vocabs/profiles/json_schema/md-profile-config/test_valid/test1.json
{
  "id": "en1fr1",
  "title": [
    {
      "lang": "de",
      "value": "Metadatenprofile für Testaufgaben: Fremdsprachen Sek I"
    }
  ],
  "mdOutDir": "docs",
  "creator": "IQB - Institut zur Qualitätsentwicklung im Bildungswesen",
  "profiles": [
    "json_schema/md-profile/test_valid/sample_1.json"
  ]
}
